import '../utils/size_config.dart';
export '../utils/size_config.dart';
class AppSizes {
  static double get paddingXs => 4.w;
  static double get paddingSm => 8.w;
  static double get paddingMd => 12.w;
  static double get paddingLg => 16.w;
  static double get paddingXl => 20.w;
  static double get paddingXxl => 24.w;
  static double get spacingXs => 4.h;
  static double get spacingSm => 8.h;
  static double get spacingMd => 12.h;
  static double get spacingLg => 16.h;
  static double get spacingXl => 20.h;
  static double get spacingXxl => 24.h;
  static double get radiusXs => 4.w;
  static double get radiusSm => 8.w;
  static double get radiusMd => 12.w;
  static double get radiusLg => 15.w;
  static double get radiusXl => 20.w;
  static double get radiusXxl => 25.w;
  static double get iconXs => 14.sp;
  static double get iconSm => 16.sp;
  static double get iconMd => 20.sp;
  static double get iconLg => 24.sp;
  static double get iconXl => 28.sp;
  static double get iconXxl => 32.sp;
  static double get fontXs => 10.sp;
  static double get fontSm => 12.sp;
  static double get fontMd => 14.sp;
  static double get fontLg => 16.sp;
  static double get fontXl => 18.sp;
  static double get fontXxl => 20.sp;
  static double get fontDisplay => 24.sp;
  static double get buttonHeight => 55.h;
  static double get inputHeight => 55.h;
  static double get controlRadius => radiusMd;
  static double get cardRadius => radiusXl;
  static double get cardElevation => 2.0;
  static double get bannerHeight => 140.h;
  static double get profileAvatarRadius => 20.w;
}
